FROM python:3.10-bullseye

ENV PYTHONUNBUFFERED 1

WORKDIR /project

COPY ./requirements-dev.txt ./
RUN pip3 --disable-pip-version-check install -r requirements-dev.txt

COPY ./ ./

CMD make start-dev