FROM python:3.10-bullseye

ENV PYTHONUNBUFFERED 1

WORKDIR /project

COPY ./requirements.txt ./
RUN pip3 --disable-pip-version-check install -r requirements.txt

COPY ./app ./app

CMD uvicorn app.main:app --host 0.0.0.0 --port 8000 --lifespan=on --loop uvloop --http httptools