name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:

jobs:
  test:
    name: "Lint and test"
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0.5
        env:
          MONGO_INITDB_DATABASE: sample
          MONGO_INITDB_ROOT_USERNAME: user
          MONGO_INITDB_ROOT_PASSWORD: pass
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install -r requirements-dev.txt

      - run: make lint

      # TODO: Tests
      # - run: pytest
      #   env:
      #     PYTHONUNBUFFERED: 1
      #     MONGO_URL: mongodb://user:pass@127.0.0.1:27017/?retryWrites=true&w=majority

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only
        if: github.ref == 'refs/heads/main'
        env:
          FLY_APP: fastapi-mongo-example
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
